1. Привести примеры метрик для оценки рекомендаций/ранжирования:
    * ERR (Expected reciprocal rank) - истинная релевантность элемента оказавшегося на определенной позиции  после сортировки по убыванию;
    * PFound - предложена специалистами Яндекса.

2. Реализовать способы расчета метрик:

In [2]:
import numpy as np

In [10]:
recommended_list = [143, 156, 1134, 991, 27, 1543, 3345, 533, 11, 43] #id товаров
bought_list = [521, 32, 143, 991]

prices_recommended = [165, 236,  20, 189, 280, 189,   6, 151, 253,  45]
prices_bought = [244, 147,  46, 146]

In [12]:
#-------------------------------------------------------------------
# оставлено для наглядности
def hit_rate(recommended_list, bought_list):
    
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)
    
    flags = np.isin(bought_list, recommended_list)
    
    hit_rate = (flags.sum() > 0) * 1
    
    return hit_rate
#-------------------------------------------------------------------

def hit_rate_at_k(recommended_list, bought_list, k=5):
#   сделать в домашней работе
    return hit_rate(recommended_list[:k], bought_list)

In [13]:
print(hit_rate(recommended_list, bought_list))
print(hit_rate_at_k(recommended_list, bought_list, 5))

1
1


In [32]:
#-------------------------------------------------------------------
# оставлено для наглядности
def precision(recommended_list, bought_list):
    
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)
    
    flags = np.isin(bought_list, recommended_list)
    
    precision = flags.sum() / len(recommended_list)
    
    return precision

#-------------------------------------------------------------------
# оставлено для наглядности
def precision_at_k(recommended_list, bought_list, k=5):
    
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)
    
    bought_list = bought_list  # Тут нет [:k] !!
    recommended_list = recommended_list[:k]
    
    flags = np.isin(bought_list, recommended_list)
    
    precision = flags.sum() / len(recommended_list)
    
    
    return precision
#-------------------------------------------------------------------

def money_precision_at_k(recommended_list, bought_list, prices_recommended, k=5):
        
#     сделать дома
    # Лучше считать через скалярное произведение, а не цикл
    
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list[:k])
    prices_recommended = np.array(prices_recommended[:k])
    
    b_prices = prices_recommended[np.isin(recommended_list, bought_list)].copy()
    
    precision = b_prices.sum() / prices_recommended.sum()
    
    return precision

In [24]:
print(precision(recommended_list, bought_list))
print(precision_at_k(recommended_list, bought_list, 5))
print(money_precision_at_k(recommended_list, bought_list, prices_recommended, 5))

0.2
0.4
0.39775280898876403


In [34]:
#-------------------------------------------------------------------
# оставлено для наглядности
def recall(recommended_list, bought_list):
    
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)
    
    flags = np.isin(bought_list, recommended_list)
    
    recall = flags.sum() / len(bought_list)
    
    return recall
#-------------------------------------------------------------------

def recall_at_k(recommended_list, bought_list, k=50):
    
    # сделать дома
    return recall(recommended_list[:k], bought_list)


def money_recall_at_k(recommended_list, bought_list, prices_recommended, prices_bought, k=5):
    
    # сделать дома
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list[:k])
    prices_recommended = np.array(prices_recommended[:k])
    prices_bought = np.array(prices_bought)
    
    b_prices = prices_recommended[np.isin(recommended_list, bought_list)].copy()
    
    recall = b_prices.sum() / prices_bought.sum()
    
    return recall

In [35]:
print(recall(recommended_list, bought_list))
print(recall_at_k(recommended_list, bought_list, 5))
print(money_recall_at_k(recommended_list, bought_list, prices_recommended, prices_bought, 5))

0.5
0.5
0.6072041166380789


In [4]:
# список из 3 пользователей
recommended_list_3_users = [[143, 156, 1134, 991, 27, 1543, 3345, 533, 11, 43], 
                    [1134, 533, 14, 4, 15, 1543, 1, 99, 27, 3345],
                    [991, 3345, 27, 533, 43, 143, 1543, 156, 1134, 11]
                           ]

bought_list_3_users = [[521, 32, 143],  # юзер 1
                       [143, 156, 991, 43, 11], # юзер 2
                       [1,2]] # юзер 3

In [36]:
a = np.array(recommended_list_3_users)
a

array([[ 143,  156, 1134,  991,   27, 1543, 3345,  533,   11,   43],
       [1134,  533,   14,    4,   15, 1543,    1,   99,   27, 3345],
       [ 991, 3345,   27,  533,   43,  143, 1543,  156, 1134,   11]])

In [39]:
for line in a:
    print(line)

[ 143  156 1134  991   27 1543 3345  533   11   43]
[1134  533   14    4   15 1543    1   99   27 3345]
[ 991 3345   27  533   43  143 1543  156 1134   11]


In [41]:
r, b

(array([ 143,  156, 1134,  991,   27]), array([521,  32, 143, 991]))

In [ ]:
#-------------------------------------------------------------------
# оставлено для наглядности
def ap_k(recommended_list, bought_list, k=5):
    
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)[:k]
    
    relevant_indexes = np.nonzero(np.isin(recommended_list, bought_list))[0]
    
    if len(relevant_indexes) == 0:
        return 0
    
    amount_relevant = len(relevant_indexes)
    
    sum_ = sum([precision_at_k(recommended_list, bought_list, k=index_relevant+1) for index_relevant in relevant_indexes])
    return sum_/amount_relevant
#-------------------------------------------------------------------

def map_k(recommended_list, bought_list, k=5):
    
    # сделать дома
    
    
    return result

In [ ]:
def reciprocal_rank(recommended_list, bought_list, k=1):
    
    # сделать дома
    return result